### PR TITLE
Get reply count from getreply url

### PR DESCRIPTION
**Pull request by jjtbsomhorst**
Added getreplycount method to retrieve the thr:count attribute so that we don't have to do an extra xhr:Get to retrieve the number of total replies on a specified topic. 

Should be tested!!!

### CODE REVIEW

**Comment by prb112** [comment]
There will need to be a test created before we merge code.  
At this time there is no plans to create the test.

**Comment by jjtbsomhorst** [comment]
To bad, because I think it is a great addition. With this code in place a developer does not have to retrieve all replies to find out the amount of replies there are.

**Comment by prb112** [comment]
I'm closing your enhancement and pull request.  I added some code that does it in one time.  it'll get the opensearch:totalResults field.  it'll include the original topic element so you may have to decrement by one.  it'll be in the 1.1.11 build - you can provide feedback and we can optimize

**Comment by jjtbsomhorst** [comment]
great
Op do 5 nov. 2015 om 23:30 schreef Paul Bastide <notifications@github.com>:

> I'm closing your enhancement and pull request. I added some code that does
> it in one time. it'll get the opensearch:totalResults field. it'll include
> the original topic element so you may have to decrement by one. it'll be in
> the 1.1.11 build - you can provide feedback and we can optimize
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenNTF/SocialSDK/pull/1725#issuecomment-154215619>.
>
-- 
Met vriendelijke groet / Yours sincerely,

Jeroen Somhorst
Abe Lenstrahof 70
6833 LP
Arnhem

Tel: 0613575092

**Pull request closed without merging**
