### PR TITLE
#1675 Extend SearchService

### PR DESCRIPTION
**Pull request by zipwiz**
This change will extend SearchService by several methods which use the MYSEARCH (authenticated) URL instead of the SEARCH (anonymous) URL.

Additionally it fixes SearchUrls.MYSEARCH by removing the trailing slash. (SEARCH is not concerned.)

There are currently no tests for SearchService at all, and I do not know how to *setup* tests, i. e. fit them with data etc. Thus I am sorry that I am not able to supply any tests for this change.

Reason: Search with "anonynous" search URL will only find public content, whereas "authenticated" search will find own and associated content, including private or restricted. This is important in scenarios which us a "system user" to create restricted content from 3rd party systems.

This pull request was started from an older but up-to-date fork-fork. Therefore there is a chain of emptry merge commits in fromt of the important one. If this is not acceptable, I must create a new fork for this.

Again I stumbled over the "pull request logic". thus there are 2 relevant commits now at the end of the chain, but they beong together anyway.

### CODE REVIEW

**Comment by prb112** [comment]
@projsaha @ManishKataria and I will review it.

**Comment by prb112** [comment]
I reviewed the code, I don't have any problems with the code.  It's the right length for non-IBM contributions to an IBM project on OpenNTF.  What I'd like you to do is add a Test for your code, it has to work in your environment, when you submit the code / tests, I'd like you to add @ignore before each test.  We'll put a task in the backlog to enable Mock Data. The Test should be contributed at this level  https://github.com/OpenNTF/SocialSDK/tree/0f7237b6ff22fed631bde9e4e16ed9744506694c/samples/j2ee/snippets/com.ibm.sbt.automation.test/src/main/java/com/ibm/sbt/test/java/connections/search

**Comment by zipwiz** [comment]
I am sorry, but I do not fully understand what you mean by "should be contributed at this level ...". I looked at the referenced class, and it declares ony 1 Test by just naming it as a snippet. There is a corresponding class declaring the "page object for the X snippet", but I did not find the connection (sic) between the snippet name and the actual method to be tested. Of course I can add a similar class declaring a snippet, but how is the corresponding "page object" declared? Where is the operation to be tested declared? Sorry again, but this confuses me :-/

**Comment by zipwiz** [comment]
I can however commit a "more usual" test class simply calling the methods in question with reasonable parameters and writing down some assertions about preconditions and postconditions. May be this is not suitable at the end, but it will show how a test should look like. Would that be OK?

**Comment by zipwiz** [comment]
I will commit a small test suite looking like the CommunityService test suite in the neighbourhood. If this is useful -- fine. If not -- please take it just as a proposal how a test should look like. I am really sorry that I do not understand how to implement a test suite based on the implementation you directed me to :-( I would need a complete example of the "ibm sbt sdk test suite implementation style".

However there are no mock data or the like. Thus the tests provided will probably not work and even maybe not fired at all because lack of configuration :-/

**Comment by zipwiz** [comment]
I will shorten this by starting again from 1.1.5-SNAPSHOT at its very start after 1.1.4-[release]. Thus I close *this* pull request to open quite the same in a cleaner shape.

**Comment by prb112** [comment]
please make two pull requests.. one for the searchurl fix, and one for the rest of the code you want to add.

**Comment by zipwiz** [comment]
On the way, starting with 1677 (deliberately not using # )

**Pull request closed without merging**
